name: [액션3] Build specific branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Build branch name'
        required: true
        default: develop
        type: string
      build_script:
        description: 'Build script'
        required: false
        default: build
        type: string

jobs:
  build:
    name: Build specific branch
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Setup environment
        run: |
          echo "VITE_GITHUB_OWNER=${{ github.repository_owner }}" >> .env
          echo "VITE_GITHUB_REPO=${{ github.event.repository.name }}" >> .env

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run ${{ github.event.inputs.build_script }}

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: unofficial-flex-extension-${{ github.event.inputs.branch }}
          path: |
            dist
